language: go

services:
  - docker
  
notifications:
  webhooks:
    urls:
      - https://us-central1-trotter-25691.cloudfunctions.net/deploy
    on_success:
     - docker rm $(docker stop $(docker ps -a -q --filter ancestor=asqwrd/trotter-api --format="{{.ID}}"))
     - docker pull asqwrd/trotter-api
     - docker run -p 3002:3002 -d asqwrd/trotter-api --restart unless-stopped
